
POOL_PATH="results/trend_etf_pool_2019_2022_optimized.csv"
DATA_DIR="data/chinese_etf/daily"
TEMP_PARAMS_PATH="config/test/macd_base_strategy_params.json"
OUTPUT_DIR="results/mega_test_macd_pool_optimized"
START_DATE="20220102"
END_DATE="20240102"

./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/1_macd_base --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/2_macd_loss_protect --enable-loss-protection --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/3_macd_enable_confirm_filter --enable-confirm-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/4_macd_enable-hysteresis --enable-hysteresis --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/5_macd_enable-trailing-stop --enable-trailing-stop --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/6_macd_enable-zero-axis --enable-zero-axis --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/7_macd_enable-adx-filter --enable-adx-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/8_macd_enable-volume-filter --enable-volume-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/9_macd_enable-hysteresis_enable-loss-protection --enable-loss-protection --enable-hysteresis --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/10_macd_enable-hysteresis_enable-trailing-stop --enable-trailing-stop --enable-hysteresis --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/11_macd_enable-hysteresis_confirm-bars-sell_2 --enable-hysteresis --confirm-bars-sell 2 --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/12_macd_enable-hysteresis_min-hold-bars_3 --enable-hysteresis --min-hold-bars 3 --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/13_macd_enable-hysteresis_enable-adx-filter --enable-hysteresis --enable-adx-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/14_macd_enable-hysteresis_enable-adx-filter_enable-trailing-stop --enable-hysteresis --enable-adx-filter --enable-trailing-stop --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/15_macd_enable-hysteresis_enable-adx-filter_enable-trailing-stop_confirm-bars-sell_2 --enable-hysteresis --enable-adx-filter --enable-trailing-stop --confirm-bars-sell 2 --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/16_macd_enable-atr-stop --enable-atr-stop --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/17_macd_enable-hysteresis_enable-trailing-stop_enable-atr-stop --enable-trailing-stop --enable-hysteresis --enable-atr-stop --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/18_macd_enable-hysteresis_enable-atr-stop --enable-hysteresis --enable-atr-stop --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/19_macd_enable-hysteresis_enable-atr-stop_enable-adx-filter --enable-hysteresis --enable-atr-stop --enable-adx-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/20_macd_enable-atr-stop_enable-volume-filter --enable-atr-stop --enable-volume-filter --start-date $START_DATE --end-date $END_DATE
./run_backtest.sh --stock-list $POOL_PATH --strategy macd_cross --optimize --data-dir $DATA_DIR --save-params $TEMP_PARAMS_PATH --output-dir $OUTPUT_DIR/21_macd_enable-hysteresis_enable-atr-stop_enable-volume-filter --enable-hysteresis --enable-atr-stop --enable-volume-filter --start-date $START_DATE --end-date $END_DATE